### ISSUE TITLE
Congratulations

### ISSUE THREAD

**Issue by emunte** [adavi4/SAI-10k-calc#1]
Congratulations on your work, I think it is going to be very useful.

Just a little suggestion, while I was trying to implement your code in an R-script I have created to semi-automatize variant classification  I received the following error:

_Error in if (str_detect(input_splice_annot$SYMBOL[1], "^RefSeqTx-")) { : 
  missing value where TRUE/FALSE needed_

My vcf file is fake, so I only have one variant (the one that I want to classify)

``
##fileformat=VCFv4.2							
##FILTER=<ID=PASS,Description="All filters passed">
##fileDate=20191004							
##reference=GRCh37/hg19							
##contig=<ID=1,length=249250621>
##contig=<ID=2,length=243199373>
##contig=<ID=3,length=198022430>
##contig=<ID=4,length=191154276>
##contig=<ID=5,length=180915260>
##contig=<ID=6,length=171115067>
##contig=<ID=7,length=159138663>
##contig=<ID=8,length=146364022>
##contig=<ID=9,length=141213431>
##contig=<ID=10,length=135534747>
##contig=<ID=11,length=135006516>
##contig=<ID=12,length=133851895>
##contig=<ID=13,length=115169878>
##contig=<ID=14,length=107349540>
##contig=<ID=15,length=102531392>
##contig=<ID=16,length=90354753>
##contig=<ID=17,length=81195210>
##contig=<ID=18,length=78077248>
##contig=<ID=19,length=59128983>
##contig=<ID=20,length=63025520>
##contig=<ID=21,length=48129895>
##contig=<ID=22,length=51304566>
##contig=<ID=X,length=155270560>
##contig=<ID=Y,length=59373566>
##INFO=<ID=SpliceAI,Number=.,Type=String,Description="SpliceAIv1.3.1 variant annotation. These include delta scores (DS) and delta positions (DP) for acceptor gain (AG), acceptor loss (AL), donor gain (DG), and donor loss (DL). Format: ALLELE|SYMBOL|DS_AG|DS_AL|DS_DG|DS_DL|DP_AG|DP_AL|DP_DG|DP_DL">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
17	41258474	c.211A>G	T	C	.	.	ADP=74;WT=0;HET=1;HOM=0;NC=0;SpliceAI=C|RefSeqTx-NM_007294.4|0.00|0.23|0.00|0.64|-346|76|32|-1
``

The problem is that when the input is loaded  REF column is interpreted as logical value.
``
input <- read_tsv(opt$in_vcf, comment="##",
                  col_types = c(`#CHROM` = "c")
``
![image](https://user-images.githubusercontent.com/49304354/232420800-4b185e94-bbc7-406b-b7de-3ab7cd42544b.png)

This is solved by also saying that REF column is character
``
input <- read_tsv(opt$in_vcf, comment="##",
                  col_types = c(`#CHROM` = "c", REF="c"))
``

I know that this may not affect many people because they will have more variants, but just for you to know.

Again, thank you for your incredible work,

Best regards,

Eli

**Comment by adavi4** [comment]
Hi Eli

Thanks so much for the wonderful feedback and for identifying this issue. This has now been fixed.

Kind regards,
Aimee
