### ISSUE TITLE
RUN spliceAI_parser

### ISSUE THREAD

**Issue by ghost** [adavi4/SAI-10k-calc#2]
Rscript spliceAI_parser.R -i output.vcf -r example_refseq_tx_hg19.txt -o example_variants_parsed.tsv

Show error

Warning messages:
1: package ‘Biostrings’ was built under R version 4.2.3 
2: package ‘S4Vectors’ was built under R version 4.2.3 
3: package ‘IRanges’ was built under R version 4.2.3 
4: package ‘XVector’ was built under R version 4.2.3 
5: package ‘GenomeInfoDb’ was built under R version 4.2.3 
Warning messages:
1: package ‘GenomicRanges’ was built under R version 4.2.3 
2: package ‘rtracklayer’ was built under R version 4.2.3 

Reference genome used:  hg19 

Pre-processing input

Prepare transcripts

Performing calculations
Warning message:
There were 2 warnings in `mutate()`.
The first warning was:
ℹ In argument: `DS_AGDG_MIN = min(DS_AG, DS_DG)`.
Caused by warning in `min()`:
! no non-missing arguments to min; returning Inf
ℹ Run `dplyr::last_dplyr_warnings()` to see the 1 remaining warning. 
Warning message:
There were 2 warnings in `mutate()`.
The first warning was:
ℹ In argument: `DS_ALDL_MIN = min(DS_AL, DS_DL)`.
Caused by warning in `min()`:
! no non-missing arguments to min; returning Inf
ℹ Run `dplyr::last_dplyr_warnings()` to see the 1 remaining warning. 
Error in `mutate()`:
ℹ In argument: `Pseudoexon_intron_info = if_else(...)`.
Caused by error in `filter()`:
ℹ In argument: `name == transcript`.
Caused by error:
! `..1` must be of size 7688 or 1, not size 0.
Backtrace:
     ▆
  1. ├─... %>% ...
  2. ├─dplyr::mutate(...)
  3. ├─tidyr::separate(...)
  4. ├─dplyr::mutate(...)
  5. ├─dplyr:::mutate.data.frame(...)
  6. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
  7. │   ├─base::withCallingHandlers(...)
  8. │   └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
  9. │     └─mask$eval_all_mutate(quo)
 10. │       └─dplyr (local) eval()
 11. ├─dplyr::if_else(...)
 12. ├─global find_pseudoexon_position(...)
 13. │ └─global make_consensus_table(transcript, refseqTab, filterNONCOD = FALSE)
 14. │   └─refseqTab %>% ungroup %>% filter(., name == transcript)
 15. ├─dplyr::filter(., name == transcript)
 16. ├─dplyr:::filter.data.frame(., name == transcript)
 17. │ └─dplyr:::filter_rows(.data, dots, by)
 18. │   └─dplyr:::filter_eval(...)
 19. │     ├─base::withCallingHandlers(...)
 20. │     └─mask$eval_all_filter(dots, env_filter)
 21. │       └─dplyr (local) eval()
 22. ├─dplyr:::dplyr_internal_error(...)
 23. │ └─rlang::abort(class = c(class, "dplyr:::internal_error"), dplyr_error_data = data)
 24. │   └─rlang:::signal_abort(cnd, .file)
 25. │     └─base::signalCondition(cnd)
 26. └─dplyr (local) `<fn>`(`<dpl:::__>`)
 27.   └─rlang::abort(message, class = error_class, parent = parent, call = error_call)
Execution halted

**Comment by adavi4** [comment]
Hi huangrongbioinfomation,

Thank you for your query. Could you please share the input files that you used to run spliceAI_parser.R

**Comment by ghost** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我已经收到邮件

**Comment by adavi4** [comment]
Issue closed due to inactivity.
