### ISSUE TITLE
Unable to reproduce the example's results

### ISSUE THREAD

**Issue by xiucz** [adavi4/SAI-10k-calc#3]
Hi, 
Thank you for your contribution. When I try to test it, I'm unable to reproduce the example's results. Can you provide some suggestions or advice?

Here is my step.
```
#make a test dir
$ cd SAI-10k-calc-main && mkdir tmp && cd  tmp
# genertate tx files
Rscript ../download_tx.R -g ../example_gene_list.txt --out_refseq example_refseq_tx_hg19.txt --out_tx_spliceai example_spliceai_tx_hg19.txt

#run spliceAi 
bgzip -c ../example_variants.vcf > example_variants.vcf.gz
tabix -p vcf example_variants.vcf.gz

~/miniconda3/envs/spliceai/bin/spliceai \
-I example_variants.vcf.gz \
-O output.vcf \
-R ~/hg19/gatk_bundle/ucsc.hg19.fasta \
-D 4999 \
-A example_spliceai_tx_hg19.txt

# run calc,
Rscript ../spliceAI_parser.R -i output.vcf -r example_refseq_tx_hg19.txt -o test.example_variants_parsed.tsv
```
Best, 
xiucz 
[test.example_variants_parsed.xls](https://github.com/adavi4/SAI-10k-calc/files/12879233/test.example_variants_parsed.xls)

**Comment by adavi4** [comment]
Hi xiucz,

Thank you for your query. We have updated our example results file to replace an outdated version. Your test results are correct.

Thanks
